--- #YAML:1.0
name:                Net-YAR
version:             1.076
abstract:            Perl interface to the YAR (Yet Another Registrar) API
license:             ~
author:              
    - Paul Seamons
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTTP::Headers:                 0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
