# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-YAR
version:      1.070
version_from: lib/Net/YAR.pm
installdirs:  site
requires:
    HTTP::Headers:                 0
    HTTP::Request:                 0
    JSON:                          0
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
